"use strict";

const properties = {
  centertankwidth: 0,
  height: 0,
  boosters: 0,
  target: 0,
  payload: 0,
  stages: 0,
  middleengines: 0,
  lowerengines: 0,
  upperengines: 0,
};
// values to be displayed

const propertiesGeneral = {
  centertankwidth: [1.0, 2.5, 3.0, 4.0, 5.0, 8.0, 9.0],
  height: [15.0, 30.0, 40.0, 50.0, 60.0, 70.0, 85.0, 95.0],
  boosters: [0, 2, 3, 4, 5, 6, 8],
  target: [
    "Low Droo Orbit",
    "High Droo orbit",
    "Droo Geosynchronous Orbit",
    "Cylero Orbit",
    "Cylero Landing",
    "Cylero Land and return",
    "Cylero Flyby",
    "Sergeaa Flyby",
    "Sergeaa Orbit",
    "Sergeaa Landing",
    "Sergeaa Land and return",
    "Vulco Flyby",
    "Vulco Orbit",
    "Vulco Landing",
    "Vulco Land and return",
    "Tydos Flyby",
    "Tydos Orbit",
    "Urados Flyby",
    "Luna Flyby",
    "Luna Orbit",
    "Luna Landing",
    "Luna Land and return",
    "Brigo Flyby",
    "Brigo Orbit",
    "Brigo Landing",
    "Brigo Land and return",
    "T.T. Flyby",
    "T.T. Orbit",
    "T.T. Landing",
    "T.T. Land and return",
    "Herma Flyby",
    "Herma Orbit",
    "Herma Landing",
    "Herma Land and return",
    "Niobe Flyby",
    "Niobe Orbit",
    "Niobe Landing",
    "Niobe Land and return",
    "Nebra Flyby",
    "Nebra Orbit",
    "Nebra Landing",
    "Nebra Land and return",
    "Orcus Flyby",
    "Orcus Orbit",
    "Orcus Landing",
    "Orcus Land and return",
    "Miros Flyby",
    "Miros Orbit",
    "Miros Landing",
    "Miros Land and return",
    "Jastrus Flyby",
    "Jastrus Orbit",
    "Jastrus Landing",
    "Jastrus Land and return",
    "Boreas Flyby",
    "Boreas Orbit",
    "Boreas Landing",
    "Boreas Land and return",
    "Taurus Flyby",
    "Taurus Orbit",
    "Taurus Landing",
    "Taurus Land and return",
    "Hypatchion Flyby",
    "Hypatchion Orbit",
    "Hypatchion Landing",
    "Hypatchion Land and return",
  ],
  payload: [
    "<1k",
    "2-5k",
    "5-10k",
    "10-20k",
    "20-35k",
    "35-50k",
    "50-75k",
    "75-100k",
    "100-150k",
    "150-200k",
    "200-250k",
    "250-300k",
    "300-350k",
    "350-400k",
    "400-450k",
    "450-500k",
    "500-550k",
    "550-600k",
    "600-650k",
    "650-700k",
  ],
  stages: [2, 3, 4, 5, 6, 7, 8],
  middleengines: [1, 2, 3, 4, 5],
  lowerengines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  upperengines: [1, 2, 3, 4, 5],
};
// values to choose from

export { properties, propertiesGeneral };
